Repository GNDVMall/GNDV-front, pull requests merged in 2024-06, with the labels that each got.

#13 dev to main 정기 PR
  index.html
  package-lock.json
  package.json
  public/logo/gndv-icon.png
  public/logo/gndv-logo1.png
  public/logo/gndv-logo2.png
  src/App.vue
  src/components/common/CommonHeader.vue
  src/components/common/Footer.vue
  src/components/common/Header.vue
  src/components/common/Layout.vue
  src/components/common/ModalContainer.vue
  src/components/icons/IconCommunity.vue
  src/components/icons/IconDocumentation.vue
  src/components/icons/IconEcosystem.vue
  src/components/icons/IconSupport.vue
  src/components/icons/IconTooling.vue
  src/components/wish/WishItem.vue
  src/router/index.js
  src/utils/axios.js
  src/utils/dateUtils.js
  src/views/ChatView.vue
  src/views/HomeView.vue
  src/views/LoginView.vue
  src/views/MyView.vue
  src/views/NoticeView.vue
  src/views/WishView.vue
Labels: enhancement

#15 Feat: 프로덕트 페이지 하드코딩 퍼블리싱 & 공통 컴포넌트
  src/components/common/Button/Button.vue
  src/components/common/ItemCard/ItemCard.vue
  src/components/common/Layout.vue
  src/components/common/ProductCard/ProductCard.vue
  src/components/common/Title/Title.vue
  src/components/items/ItemDetailCard.vue
  src/components/items/ItemImage.vue
  src/components/items/ItemSubInfo.vue
  src/components/items/ItemTitle.vue
  src/components/items/ProductsList.vue
  src/router/index.js
  src/views/ItemView.vue
  src/views/TestView.vue
Labels: enhancement

#16 Feat: 상태관리 추가
  src/components/common/ProfileWithStar/ProfileWithStar.vue
  src/components/product/ProductDetailCard.vue
  src/components/product/RecommendList.vue
  src/components/product/UserInfo.vue
  src/router/index.js
  src/store/store.js
  src/utils/axios.js
  src/views/ProductView.vue
Labels: feat

#17 Feat: Suspense 적용 & 그에 맞춰서 Axios 변경
  src/App.vue
  src/components/common/Layout.vue
  src/utils/axios.js
Labels: enhancement

#20 Feat: 데이터를 가져오는 방식을 기본 방식으로 다시 변경
  src/App.vue
  src/utils/axios.js
Labels: feat

#21 Feat: Item&Product 페이지 api 연결 #19
  src/components/common/Pagination/Pagination.vue
  src/components/common/ProductCard/ProductCard.vue
  src/components/items/ItemDetailCard.vue
  src/components/items/ProductsList.vue
  src/components/product/ProductDetailCard.vue
  src/components/product/UserInfo.vue
  src/utils/currency.js
  src/utils/dateUtils.js
  src/views/ProductView.vue
Labels: enhancement

#23 refactor: 안전거래버튼 연결
  package-lock.json
  package.json
  src/App.vue
  src/components/common/ItemCard/ItemCard.vue
  src/components/common/ItemCard/WishListButton.vue
  src/components/common/Layout.vue
  src/components/order/OrderHistory.vue
  src/components/payments/PaymentButton.vue
  src/components/payments/TestLoginComponent.vue
  src/components/product/ProductDetailCard.vue
  src/main.js
  src/router/index.js
  src/store/store.js
  src/utils/axios.js
  src/utils/importIamport.js
  src/views/LoginView.vue
  src/views/OrderTest.vue
  src/views/PaymentTest.vue
  src/views/PurchaseList.vue
  src/views/TestProductDetail.vue
  src/views/TestProductList.vue
Labels: feat

#24 fix: 임시 로그인 기능이 제대로 토큰을 사용하도록 수정
  src/components/payments/TestLoginComponent.vue
  src/utils/axios.js
Labels: bug, enhancement

#25 feat : wish list 구현
  src/components/common/Button/Button.vue
  src/components/items/ItemDetailCard.vue
  src/components/product/ProductDetailCard.vue
  src/components/wish/WishItem.vue
  src/components/wish/WishListButton.vue
  src/views/WishView.vue
Labels: feat

#26 Feat: 채팅 페이지 #22
  package-lock.json
  package.json
  src/components/chat/ChatHeader.vue
  src/components/chat/ChatInput.vue
  src/components/chat/ChatItemCard.vue
  src/components/chat/ChatMain.vue
  src/components/chat/ChatMessage.vue
  src/components/chat/ChatRoomSideItem.vue
  src/components/chat/ChatSide.vue
  src/components/chat/ChatViewGrid.vue
  src/components/payments/TestLoginComponent.vue
  src/components/product/ProductDetailCard.vue
  src/router/index.js
  src/store/store.js
  src/utils/dateUtils.js
  src/views/ChatView.vue
  src/websocket/websocket.js
Labels: enhancement

#27 Feat/chatting ayo #22
  src/components/chat/ChatHeader.vue
  src/components/chat/ChatInput.vue
  src/components/chat/ChatMain.vue
  src/components/chat/ChatMessage.vue
  src/components/chat/ChatSide.vue
  src/components/product/ProductDetailCard.vue
  src/router/index.js
Labels: enhancement

#29 feat: 리뷰작성 기능
  package-lock.json
  package.json
  src/components/chat/ChatHeader.vue
  src/components/chat/ChatInput.vue
  src/components/chat/ChatMain.vue
  src/components/common/ModalContainer.vue
  src/components/common/ProfileWithStar/ProfileWithStar.vue
  src/components/common/ProfileWithStar/Star.vue
  src/components/common/Sidebar.vue
  src/components/order/OrderHistory.vue
  src/components/order/OrderItem.vue
  src/components/order/SalesHistory.vue
  src/components/order/SalesItem.vue
  src/components/payments/PaymentButton.vue
  src/components/product/ProductDetailCard.vue
  src/router/index.js
  src/store/store.js
  src/views/MyView.vue
  src/views/ReviewForm.vue
  src/views/WishView.vue
Labels: enhancement, feat

#32 중간저장
  src/components/chat/ChatHeader.vue
  src/components/chat/ChatItemCard.vue
  src/components/modal/BuyerReviewModal.vue
  src/components/modal/ModalContainer.vue
  src/components/modal/SellerReviewModal.vue
  src/components/order/OrderHistory.vue
  src/components/order/OrderItem.vue
  src/components/order/SalesHistory.vue
  src/components/order/SalesItem.vue
  src/router/index.js
  src/views/ReviewDetail.vue
  src/views/ReviewForm.vue
Labels: enhancement

#33 Feat/search imhungry2
  src/components/common/Header.vue
  src/components/common/ItemCard/ItemCard.vue
  src/components/search/SearchModal.vue
  src/router/index.js
  src/views/SearchResultsView.vue
  src/views/SearchView.vue
Labels: enhancement

#34 Feat: 채팅 이미지 기능 완성
  src/components/chat/ChatInput.vue
  src/components/chat/ChatItemCard.vue
  src/components/chat/ChatMain.vue
  src/components/chat/ChatMessage.vue
  src/components/chat/ChatRoomSideItem.vue
  src/components/chat/ChatSide.vue
  src/components/common/ItemCard/WishListButton.vue
Labels: enhancement

#35 feat: 리뷰기능
  src/components/chat/ChatItemCard.vue
  src/components/modal/BuyerReviewModal.vue
  src/components/order/OrderHistory.vue
  src/components/order/SalesHistory.vue
  src/components/order/SalesItem.vue
  src/router/index.js
Labels: enhancement

#36 Fix/product profile ayo
  src/components/common/Header.vue
  src/components/common/ProfileWithStar/ProfileWithStar.vue
  src/components/product/UserInfo.vue
Labels: bug

#37 feat: 회원가입
  src/App.vue
  src/components/auth/LoginComponent.vue
  src/components/auth/SignupComponent.vue
  src/components/chat/ChatHeader.vue
  src/components/chat/ChatMain.vue
  src/components/chat/ChatSide.vue
  src/components/common/Header.vue
  src/components/modal/BuyerReviewModal.vue
  src/components/modal/SellerReviewModal.vue
  src/components/order/OrderHistory.vue
  src/components/order/SalesHistory.vue
  src/components/payments/TestLoginComponent.vue
  src/components/product/ProductForm.vue
  src/components/search/SearchModal.vue
  src/components/wish/WishItem.vue
  src/components/wish/WishListButton.vue
  src/main.js
  src/router/index.js
  src/store/store.js
  src/utils/axios.js
  src/views/LoginView.vue
  src/views/ReviewDetail.vue
  src/views/ReviewForm.vue
  src/views/SearchResultsView.vue
  src/views/WishView.vue
Labels: enhancement

#38 Feat/serach ayo
  src/components/chat/ChatHeader.vue
  src/components/chat/ChatMain.vue
  src/components/common/Footer.vue
  src/components/common/ItemCard/ItemCard.vue
  src/components/search/SearchInput.vue
  src/components/search/SearchList.vue
  src/components/search/SearchModal.vue
  src/components/search/SearchSidebar.vue
  src/components/search/SearchWrapper.vue
  src/utils/axios.js
  src/views/SearchResultsView.vue
  src/websocket/websocket.js
Labels: enhancement

#39 Feat: 회원가입 이메일 체크 일부 변경, 검색 결과 페이지
  src/components/auth/SignupComponent.vue
  src/components/search/SearchList.vue
  src/components/search/SearchModal.vue
  src/components/search/SearchSidebar.vue
  src/store/store.js
Labels: enhancement

#40 Feat: 검색 결과 페이지 필터 기능 적용
  src/components/common/Header.vue
  src/components/common/ItemCard/ItemCard.vue
  src/components/search/SearchInput.vue
  src/components/search/SearchList.vue
  src/components/search/SearchModal.vue
  src/components/search/SearchSidebar.vue
Labels: enhancement

#41 Feat: 유저 프로필 정보 페이지 퍼블리싱 완료
  src/components/common/CommonHeader.vue
  src/components/common/Header.vue
  src/components/common/ProfileWithStar/ProfileWithStar.vue
  src/components/common/Star/ReadOnlyStar.vue
  src/components/common/Star/Star.vue
  src/components/modal/BuyerReviewModal.vue
  src/components/modal/SellerReviewModal.vue
  src/components/publicProfile/Review.vue
  src/components/publicProfile/UserProfileCard.vue
  src/components/publicProfile/UserReviewList.vue
  src/router/index.js
  src/views/PublicUserProfileView.vue
  src/views/ReviewForm.vue
Labels: enhancement

#42 feat : 프로필 정보
  src/components/auth/LoginComponent.vue
  src/components/common/Sidebar.vue
  src/components/modal/ProfileModal.vue
  src/components/order/OrderItem.vue
  src/components/product/ProductDetailCard.vue
  src/components/search/SearchModal.vue
  src/router/index.js
  src/store/store.js
  src/utils/axios.js
  src/views/LoginInfo.vue
  src/views/MyView.vue
  src/views/Profile.vue
Labels: enhancement

#44 Fix: 채팅 입력이 두번씩 되는 현상 수정
  src/components/chat/ChatInput.vue
Labels: bug

#47 Feat: 유저 정보 페이지 api 연결 완성
  src/components/chat/ChatMessage.vue
  src/components/chat/ChatSide.vue
  src/components/items/ItemDetailCard.vue
  src/components/items/ItemImage.vue
  src/components/product/ProductDetailCard.vue
  src/components/publicProfile/Review.vue
  src/components/publicProfile/UserProfileCard.vue
  src/components/publicProfile/UserProfileWrapper.vue
  src/components/publicProfile/UserReviewList.vue
  src/components/search/SearchModal.vue
  src/router/index.js
Labels: enhancement

#48 feat: mainpage
  src/assets/img/lego1.webp
  src/assets/img/lego2.jpeg
  src/assets/img/lego3.jpeg
  src/components/common/ProductCard/RecentProductList.vue
  src/components/common/carousel/CarouselComponent.vue
  src/utils/axios.js
  src/views/HomeView.vue
  src/views/LoginView.vue
Labels: enhancement

#49 Feat: 검색 페이지네이션 & 메인페이지 테마
  src/App.vue
  src/components/common/Button/Button.vue
  src/components/common/ProductCard/RecentProductList.vue
  src/components/common/Sidebar.vue
  src/components/common/Star/ReadOnlyStar.vue
  src/components/items/ProductsList.vue
  src/components/product/ProductDetailCard.vue
  src/components/publicProfile/Review.vue
  src/components/publicProfile/UserProfileWrapper.vue
  src/components/publicProfile/UserReviewList.vue
  src/components/search/SearchList.vue
  src/components/search/SearchSidebar.vue
  src/components/theme/ThemeCard.vue
  src/components/theme/ThemeList.vue
  src/router/index.js
  src/views/HomeView.vue
  src/views/LoginView.vue
  src/views/NotFound.vue
  src/views/PublicUserProfileView.vue
  src/views/TestProductDetail.vue
  src/views/TestProductList.vue
  src/views/TestView.vue
Labels: enhancement

#50 style: 이미지 객체 컬럼명 변경
  src/components/items/ItemDetailCard.vue
Labels: bug

#51 Fix/버그수정 ayo
  src/components/chat/ChatHeader.vue
  src/components/chat/ChatMain.vue
  src/components/chat/ChatMessage.vue
  src/components/common/Header.vue
  src/components/publicProfile/UserProfileCard.vue
  src/components/publicProfile/UserProfileWrapper.vue
  src/components/publicProfile/UserReviewList.vue
  src/router/index.js
  src/views/MyProfileView.vue
  src/views/ReviewForm.vue
Labels: bug

#52 Fix: 리뷰 리스트를 제대로 출력하도록 버그 수정
  src/components/publicProfile/UserProfileCard.vue
  src/components/publicProfile/UserProfileWrapper.vue
  src/views/HomeView.vue
Labels: bug

#54 Feat/판매완료처리
  src/components/common/ProductCard/ProductCard.vue
  src/components/items/ProductsList.vue
  src/components/product/ProductDetailCard.vue
Labels: enhancement

#56 fix: my/wish
  src/components/common/Sidebar.vue
  src/components/order/SalesHistory.vue
Labels: enhancement

#58 Fix/버그수정 ayo
  src/components/common/Button/Button.vue
  src/components/common/ProductCard/ProductCard.vue
  src/components/items/ItemDetailCard.vue
  src/components/items/ItemSubInfo.vue
  src/components/items/ProductsList.vue
  src/components/payments/PaymentButton.vue
  src/components/product/ProductDetailCard.vue
  src/views/ProductView.vue
Labels: bug

#59 fix
  src/components/wish/WishItem.vue
Labels: enhancement

#67 Fix: 계속 정리중
  src/components/auth/LoginComponent.vue
  src/components/chat/ChatHeader.vue
  src/components/chat/ChatInput.vue
  src/components/chat/ChatItemCard.vue
  src/components/chat/ChatMain.vue
  src/components/chat/ChatMessage.vue
  src/components/chat/ChatRoomSideItem.vue
  src/components/chat/ChatSide.vue
  src/components/common/Header.vue
  src/components/common/ProductCard/RecentProductList.vue
  src/components/modal/BuyerReviewModal.vue
  src/components/modal/LoginModal.vue
  src/components/modal/SellerReviewModal.vue
  src/components/order/OrderHistory.vue
  src/components/order/SalesHistory.vue
  src/components/product/ProductDetailCard.vue
  src/components/product/ProductForm.vue
  src/components/publicProfile/UserReviewList.vue
  src/components/search/SearchList.vue
  src/components/theme/ThemeList.vue
  src/views/LoginInfo.vue
  src/views/MyProfileView.vue
  src/views/MyView.vue
  src/views/Profile.vue
  src/views/SearchResultsView.vue
  src/views/WishView.vue
Labels: enhancement

#69 Fix: 리뷰 버그 수정
  src/components/chat/ChatHeader.vue
  src/components/common/ItemCard/ItemCard.vue
  src/components/wish/WishListButton.vue
  src/views/ReviewForm.vue
Labels: enhancement

#77 핸드폰인증
  package-lock.json
  src/components/modal/SmsConfirmModal.vue
  src/components/modal/SmsModal.vue
  src/views/LoginInfo.vue
  vite.config.js
Labels: enhancement
